### PUT local
PUT http://localhost:7071/api/numbers/foo

### GET local
GET http://localhost:7071/api/numbers/foo

### GET Conflicts local
GET http://localhost:7071/api/conflicts/foo

### GET local
GET http://localhost:7071/


### PUT prod AUE
PUT https://numberservice-aue.azurewebsites.net/api/numbers/free?diagnostics

### GET prod AUE
GET https://numberservice-aue.azurewebsites.net/api/numbers/free

### PUT prod ASE
PUT https://numberservice-ase.azurewebsites.net/api/numbers/free?diagnostics

### GET prod ASE
GET https://numberservice-ase.azurewebsites.net/api/numbers/free

### GET Conflicts AUE
GET https://numberservice-aue.azurewebsites.net/api/conflicts/free

### GET Conflicts ASE
GET https://numberservice-ase.azurewebsites.net/api/conflicts/free
