$location = 'australiaeast'
$loc = 'aue'
$rg = 'numberservice-rg'
$tags = 'project=NumberService', 'repo=DanielLarsenNZ/NumberService'
$insights = 'numberservice-insights'
$cosmos = 'numberservice4'
$cosmosDB = 'NumberService'
$container = 'Numbers'
